language: node_js
node_js:
  - 12
before_script:
  - export CI=true
services:
  - mongodb
install:
  - cd ./src/backend && yarn install

script:
  - echo $cleverMongoDbfile > config/cleverMongoDb.js
  - yarn test
