language: node_js
node_js:
  - "stable"
  - "11"
before_script:
  - export CI=true
services:
  - mongodb
install:
  - cd ./src/backend && yarn install
  - cd ../frontend && yarn install
script:
  - cd ./src/backend && yarn test
