language: node_js
node_js:
  - "stable"
before_script:
  - export CI=true
services:
  - mongodb
install:
  - cd ./src/frontend&& yarn install
  - cd ../backend && yarn install

script:
  - echo $cleverMongoDbfile >config/cleverMongoDb.json
  - yarn test
