# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - moh-data-collection

on:
  push:
    branches:
      - dev-david

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        cd src/frontend
        yarn install 

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'moh-data-collection'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_87423bc93cc94f20abeedadf42aee15b }}
        package: .
